
name: Waka Readme2

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # runs at 12 AM UTC (5:30 AM IST)
    - cron: "0 */12 * * *" 

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master # this action name
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          COMMIT_MESSAGE: "Updated simple waka stats section"
          SHOW_TITLE: true # optional
          SECTION_NAME: aim # optional
          LANG_COUNT: 20 # optional
          STOP_AT_OTHER: true # optional
          TIME_RANGE: all_time # optional
          SHOW_TIME: true # optional
          SHOW_TOTAL: true # optional
          SHOW_MASKED_TIME: false # optional
